server:
  port: 9001

#spring-hibernate for mysql
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  #connection MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/db_foods?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: nhanbn98

google:
  clientId: 569599946060-9s09k2ujflc4ar0p5fsml7t6d78i3a0v.apps.googleusercontent.com
  secretPsw: kjsfdhkjhfdslhfdslhfdsuiuuiywe
